# Simple workflow for putting runner logs in Pull Request comments
name: Comment Runner Log
run-name: Commenting ${{ (inputs.failed_only == true && 'FAILED Run' || '') }} On ${{ inputs.branch_name }} Pull Request

on:
  # Allows you to run this workflow manually from the Actions tab AND from other actions (fwTaskPushCreateCheck)
  workflow_dispatch:
    inputs:
      run_id:
        description: Run ID
        required: true
      repo_name:
        description: Repository Name
        required: true
      branch_name:
        description: Branch Name
        required: true
      failed_only:
        description: "Only Failed Logs"
        type: boolean
        default: true
      line_limit:
        description: "Max Report Lines"
        default: "50"
      

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pull-requests: write

# Allow one concurrent deployment
concurrency:
  group: "commentLog"
  cancel-in-progress: true

jobs:
  comment:
    env:
      ACTIONS_RUNNER_DEBUG: true 
      GH_TOKEN: ${{ github.token }}
    runs-on: self-hosted
    steps:
      # Set Output After Delay For Trigger Workflow To Finish
      - name: Sleep for 5 seconds
        run: Start-Sleep -s 5
        shell: powershell
      
      # - name: Get Output
      #   id: log
      #   run: |
      #     echo "LOG=$( gh run view ${{ inputs.run_id }} --log ) >> $env:GITHUB_OUTPUT
      # - name: Debug Log
      #   run: |
      #     echo ${{ steps.log.outputs.LOG || 'none'}}
      # - name: Comment Pull Request With Log
      #   run: |
      #     gh pr comment --body "${{ toJSON(steps.log.outputs.LOG || 'none' ) }}"
      - name: Log To File
        if: ${{ !inputs.failed_only }}
        run: |
          gh run view ${{ inputs.run_id }} --log > output.log
      - name: Log To File Failed Only
        if: ${{ inputs.failed_only }}
        run: |
          gh run view ${{ inputs.run_id }} --log-failed > output.log
      - name: Remove control characters
        run: |
          Get-Content output.log -Encoding UTF8 -Tail "${{ inputs.line_limit }}" | Set-Content outputUTF8.log
      - name: Comment Pull Request With Log
        run: |
          gh pr comment -R ${{ inputs.repo_name }} ${{ inputs.branch_name }} --body-file outputUTF8.log
      


      